FROM golang:1.6.2

ENV PROJECT_PATH=/go/src/github.com/brocaar
ENV PATH=$PATH:$PROJECT_PATH/build

# install tools
RUN go get github.com/golang/lint/golint
RUN go get github.com/kisielk/errcheck

# setup work directory
RUN mkdir -p $PROJECT_PATH
WORKDIR $PROJECT_PATH
RUN git clone https://github.com/brocaar/lora-gateway-bridge/releases/tag/2.1.2
WORKDIR $PROJECT_PATH/lora-gateway-bridge
RUN make build
